### ISSUE TITLE
x,y,z coordinates instead?

### ISSUE THREAD

**Issue by rclark** [Turfjs/turf-planepoint#1]
The api would make a little more sense to me if you were to define the plane as a polygon with `[x, y, z]` coordinates instead of `{a: z1, b: z2, c: z3}` properties? Could we have it both ways?

**Comment by morganherlocker** [comment]
@rclark yeah, this is definitely gross. We can switch this to x,y,z. This will effect [tin](https://github.com/Turfjs/turf-tin) and [isolines](https://github.com/Turfjs/turf-isolines), but the tradeoff seems well worth it. I say we simply remove the a,b,c thing.

**Comment by tmcw** [comment]
Actually, this is no longer kosher in the land of GeoJSON IETF draft

> An OPTIONAL third
>    position element SHALL be the height in meters above or below the WGS
>    84 reference ellipsoid.

The shall means that _if_ the 3rd is supplied _then it must_ be altitude. Given that planepoint is not necessarily dealing with altitude, we shouldn't use the Z value imho.
